### ISSUE TITLE
Clear cache for _xxx.js

### ISSUE THREAD

**Issue by xcatliu** [xcatliu/pagic#7]
`_xxx.js` always used as a partial layout, we need to clear it's cache when modify it.

**Comment by yoshixmk** [comment]
This issue contains static image support?
It seems that the image disappears when I place the image on the top page, move to the subdirectory, and return from the link. 
I try to place relative path and absolute path for localy static image, cannot show it.
https://github.com/yoshixmk/profile/tree/gh-pages

**Comment by xcatliu** [comment]
Not quite understand your problem.
I tried https://yoshixmk.github.io/profile/ and the image shows correctly.

Both relative and absolute path should works fine in pagic.

Can you provide an example that shows your case? Or describe the reproduction steps.

**Comment by yoshixmk** [comment]
I'm sorry. I gave a difficult explanation.

1. https://yoshixmk.github.io/profile/ (image is displayed)
1.  Click the link sidebar "ブログ" to go to another page. ( For example, https://yoshixmk.github.io/profile/articles/index.html )
1.  The link sidebar "@yoshixmk / Yoshihiro Ueki" returns you to the original page. https://yoshixmk.github.io/profile/index.html (The image is not displayed.)
The cause seems to be that the /articles/ path has been included. I saw this in html but it doesn't seem to be a problem so I wondered if JS is working
```
o https://yoshixmk.github.io/profile/static/images/usagi.jpg
x https://yoshixmk.github.io/profile/articles/static/images/usagi.jpg
```

**Comment by xcatliu** [comment]
@yoshixmk Bug confirmed. I will fix it in the next version. Thank you for your report!

**Comment by xcatliu** [comment]
@yoshixmk Upgrade to 0.7.8 should solve this problem

**Comment by yoshixmk** [comment]
@xcatliu  哇！ 目录功能非常方便！ 我将立即使用它！ 谢谢！

**Comment by xcatliu** [comment]
@yoshixmk 欢迎使用！欢迎提更多的建议！

**Comment by xcatliu** [comment]
It's impossible to clear cache for `_xxx.ts`, because such module is import by an other module, we can't change the `import` statement.
Close this issue
